In [1]:
import numpy as np

In [2]:
from scipy import linalg

In [3]:
A = np.mat([[1, 2], [3, 4]])
# Умножает для типаnp.mat по правилам матричной алгебры

In [4]:
B = np.mat([[1, 2], [3, 4]])

In [5]:
A*B

matrix([[ 7, 10],
        [15, 22]])

In [6]:
A = np.array([[1, 2], [3, 4]])
#Для типа np.array умножает поэлементно

In [7]:
B = np.array([[1, 2], [3, 4]])

In [8]:
A*B

array([[ 1,  4],
       [ 9, 16]])

In [9]:
A = np.mat([[1, 2], [3, 4]])

In [10]:
b = np.mat([1, 2])

In [11]:
A*b.T
#1)Трансапонирования матрицы чтобы считало с сразным кол-во стобцов

matrix([[ 5],
        [11]])

In [12]:
b = np.mat([[1], [2]])
#2)Вариант

In [13]:
A*b

matrix([[ 5],
        [11]])

In [14]:
Ai = linalg.inv(A) #преобразуетует матрицу в обратную матрицу

In [15]:
Ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
A*Ai # ПОдтверждение 

matrix([[1.0000000e+00, 0.0000000e+00],
        [8.8817842e-16, 1.0000000e+00]])

In [17]:
# Метод програмного решения обратной матрицы с картинки 

In [18]:
A = np.mat([[1, 3, 5],[2, 5, 1],[2, 3, 8]])

In [19]:
b = np.mat([[10],[8],[3]])

In [20]:
x = linalg.inv(A).dot(b) 
# 1 способ (медленный)

In [21]:
x

matrix([[-9.28],
        [ 5.16],
        [ 0.76]])

In [22]:
x = linalg.solve(A,b) 
# Решение СЛУ.функция solve (более быстрый)

In [23]:
x

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [27]:
detA = linalg.det(A) # Вычисление определителя матрицы(Детраинант)

In [28]:
detA

-25.000000000000004

In [29]:
# Собственные числа и вектора

In [30]:
A = np.mat([[1, 2], [3, 4]])

In [31]:
lamb, v = linalg.eig(A)

In [32]:
lamb # возвращает собственные значание

array([-0.37228132+0.j,  5.37228132+0.j])

In [33]:
v # Собстванные вектора

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])