In [1]:
import numpy as np

In [2]:
M1 = np.identity( 4,dtype=np.float32)

In [3]:
M1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [16]:
M1[1,3] = 1

In [18]:
M1[3,2] = 3

In [19]:
M1

array([[1., 3., 7., 7.],
       [0., 1., 3., 1.],
       [0., 0., 1., 0.],
       [0., 0., 3., 1.]], dtype=float32)

In [20]:
from itertools import product

In [21]:
def fill_zeros( M ):
    R, C = M.shape
    R = range(0,R)
    C = range(0,C)
    for i,k in product(R,C):
        if M[i,k] == 0:
            M[i,k] = 1/M[k,i]

In [22]:
fill_zeros(M1)

In [23]:
M1

array([[1.        , 3.        , 7.        , 7.        ],
       [0.33333334, 1.        , 3.        , 1.        ],
       [0.14285715, 0.33333334, 1.        , 0.33333334],
       [0.14285715, 1.        , 3.        , 1.        ]], dtype=float32)

In [25]:
np.linalg.eig(M1)

(array([ 4.1267595e+00+0.j        , -6.3379698e-02+0.72047794j,
        -6.3379698e-02-0.72047794j, -1.0518467e-08+0.j        ],
       dtype=complex64),
 array([[ 9.3730772e-01+0.j        ,  9.6967179e-01+0.j        ,
          9.6967179e-01-0.j        ,  6.0118047e-08+0.j        ],
        [ 2.5808930e-01+0.j        , -9.4189398e-02-0.06367329j,
         -9.4189398e-02+0.06367329j, -9.5257932e-01+0.j        ],
        [ 9.3240224e-02+0.j        , -3.5126176e-02-0.06362246j,
         -3.5126176e-02+0.06362246j,  2.7216554e-01+0.j        ],
        [ 2.1482660e-01+0.j        , -7.1811132e-02+0.1907149j ,
         -7.1811132e-02-0.1907149j ,  1.3608275e-01+0.j        ]],
       dtype=complex64))