In [4]:
import numpy as np
import cv2
from skimage import img_as_float
%matplotlib inline
from skimage.io import imread, imshow, imsave

# Загрузка цветного изображения как полутонового  в виде табицы
img1 = cv2.imread('/Users/zaha/Downloads/КБ Луч/1.png',0)
img2 = cv2.imread('/Users/zaha/Downloads/КБ Луч/2.png',0)


In [5]:
img1.shape # ( Строки,Столбы,кол-во каналовRGB)


(750, 1000)

In [6]:
img2.shape # ( Строки,Столбы,кол-во каналовRGB)

(750, 1000)

In [7]:
img1.size

750000

In [8]:
img2.size

750000

In [9]:
img1[:]

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 25, 25, 30],
       [ 0,  0,  0, ..., 22, 21, 25],
       [ 0,  0,  0, ..., 22, 21, 29]], dtype=uint8)

In [10]:
img2[:]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [11]:
diap = [img1+283, img1+311]
img2 = diap

In [12]:
img2 = img_as_float(img2)
img1 = img_as_float(img1)

In [13]:
img1.dtype

dtype('float64')

In [14]:
img2

array([[[0.0043183 , 0.0043183 , 0.0043183 , ..., 0.0043183 ,
         0.0043183 , 0.0043183 ],
        [0.0043183 , 0.0043183 , 0.0043183 , ..., 0.0043183 ,
         0.0043183 , 0.0043183 ],
        [0.0043183 , 0.0043183 , 0.0043183 , ..., 0.0043183 ,
         0.0043183 , 0.0043183 ],
        ...,
        [0.0043183 , 0.0043183 , 0.0043183 , ..., 0.00469978,
         0.00469978, 0.00477607],
        [0.0043183 , 0.0043183 , 0.0043183 , ..., 0.004654  ,
         0.00463874, 0.00469978],
        [0.0043183 , 0.0043183 , 0.0043183 , ..., 0.004654  ,
         0.00463874, 0.00476081]],

       [[0.00474556, 0.00474556, 0.00474556, ..., 0.00474556,
         0.00474556, 0.00474556],
        [0.00474556, 0.00474556, 0.00474556, ..., 0.00474556,
         0.00474556, 0.00474556],
        [0.00474556, 0.00474556, 0.00474556, ..., 0.00474556,
         0.00474556, 0.00474556],
        ...,
        [0.00474556, 0.00474556, 0.00474556, ..., 0.00512703,
         0.00512703, 0.00520333],
        [0.0

In [15]:
print(img1.min(), img1.max())
print(img2.min(), img2.max())

0.0 1.0
0.004318303196765088 0.008636606393530175


In [16]:
ssd = sum(img1**2-img2**2)

In [17]:
ssd

array([[-4.11680424e-05, -4.11680424e-05, -4.11680424e-05, ...,
        -4.11680424e-05, -4.11680424e-05, -4.11680424e-05],
       [-4.11680424e-05, -4.11680424e-05, -4.11680424e-05, ...,
        -4.11680424e-05, -4.11680424e-05, -4.11680424e-05],
       [-4.11680424e-05, -4.11680424e-05, -4.11680424e-05, ...,
        -4.11680424e-05, -4.11680424e-05, -4.11680424e-05],
       ...,
       [-4.11680424e-05, -4.11680424e-05, -4.11680424e-05, ...,
         1.91750013e-02,  1.91750013e-02,  2.76317754e-02],
       [-4.11680424e-05, -4.11680424e-05, -4.11680424e-05, ...,
         1.48391032e-02,  1.35168316e-02,  1.91750013e-02],
       [-4.11680424e-05, -4.11680424e-05, -4.11680424e-05, ...,
         1.48391032e-02,  1.35168316e-02,  2.58173928e-02]])

In [18]:
img1.mean()

0.3898138823529412

In [19]:
img2.mean()

0.006048715037766076

In [20]:
men = img1.mean() - img2.mean()

In [21]:
men

0.3837651673151751

In [22]:
N = 49

In [23]:
R = ssd / N - (men**2)

In [24]:
R

array([[-0.14727654, -0.14727654, -0.14727654, ..., -0.14727654,
        -0.14727654, -0.14727654],
       [-0.14727654, -0.14727654, -0.14727654, ..., -0.14727654,
        -0.14727654, -0.14727654],
       [-0.14727654, -0.14727654, -0.14727654, ..., -0.14727654,
        -0.14727654, -0.14727654],
       ...,
       [-0.14727654, -0.14727654, -0.14727654, ..., -0.14688438,
        -0.14688438, -0.14671179],
       [-0.14727654, -0.14727654, -0.14727654, ..., -0.14697286,
        -0.14699985, -0.14688438],
       [-0.14727654, -0.14727654, -0.14727654, ..., -0.14697286,
        -0.14699985, -0.14674882]])

In [27]:
min(*R)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [28]:
d1

NameError: name 'd1' is not defined

In [29]:
ssd2 = sum(img2**2-img1**2)

In [30]:
ssd2

array([[ 4.11680424e-05,  4.11680424e-05,  4.11680424e-05, ...,
         4.11680424e-05,  4.11680424e-05,  4.11680424e-05],
       [ 4.11680424e-05,  4.11680424e-05,  4.11680424e-05, ...,
         4.11680424e-05,  4.11680424e-05,  4.11680424e-05],
       [ 4.11680424e-05,  4.11680424e-05,  4.11680424e-05, ...,
         4.11680424e-05,  4.11680424e-05,  4.11680424e-05],
       ...,
       [ 4.11680424e-05,  4.11680424e-05,  4.11680424e-05, ...,
        -1.91750013e-02, -1.91750013e-02, -2.76317754e-02],
       [ 4.11680424e-05,  4.11680424e-05,  4.11680424e-05, ...,
        -1.48391032e-02, -1.35168316e-02, -1.91750013e-02],
       [ 4.11680424e-05,  4.11680424e-05,  4.11680424e-05, ...,
        -1.48391032e-02, -1.35168316e-02, -2.58173928e-02]])

In [31]:
men2 = img2.mean() - img1.mean()

In [32]:
men2

-0.3837651673151751

In [33]:
R1 = ssd2 / N - (men2**2)

In [34]:
R1

array([[-0.14727486, -0.14727486, -0.14727486, ..., -0.14727486,
        -0.14727486, -0.14727486],
       [-0.14727486, -0.14727486, -0.14727486, ..., -0.14727486,
        -0.14727486, -0.14727486],
       [-0.14727486, -0.14727486, -0.14727486, ..., -0.14727486,
        -0.14727486, -0.14727486],
       ...,
       [-0.14727486, -0.14727486, -0.14727486, ..., -0.14766703,
        -0.14766703, -0.14783962],
       [-0.14727486, -0.14727486, -0.14727486, ..., -0.14757854,
        -0.14755156, -0.14766703],
       [-0.14727486, -0.14727486, -0.14727486, ..., -0.14757854,
        -0.14755156, -0.14780259]])

In [35]:
d2 = min(R)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [36]:
d2

NameError: name 'd2' is not defined