In [1]:
import numpy as np
import cv2
from skimage import img_as_float
import os


In [ ]:
answer = ''
while answer != 'q':
    answer = input("1 - Построить карту диспаритета при изветном диапозоне сдвига диспаритета от 283 до 311\n2 - Построить карту диспаритета при изветном диапозоне сдвига диспаритета от -311 до -283\n3 - Вывевести преобразованные изображения (1/2/3)")
    if  answer == '1':
        img1 = cv2.imread('/Users/zaha/Downloads/КБ Луч/1.png',0)
        img2 = cv2.imread('/Users/zaha/Downloads/КБ Луч/2.png',0)
        
        diap = [img1+283, img1+311]
        img2 = diap
        img2 = np.asarray(img2, dtype=np.uint8)
        ssd = sum(img1-img2)**2
        men = img1.mean() - img2.mean()
        N = 750000

        R = ssd / N - (men**2)
        R = np.asarray(R, dtype=np.uint8)
        print('Вывести информацию о размере массиве R(d) изображения',R.shape, '\nКоличество пикселей:', R.size, '\nМассив R(d):\n', R)
        d1 = np.amin(R)
        print('Диспаритет:', d1)
        
        
        
    elif  answer == '2':
        img1 = cv2.imread('/Users/zaha/Downloads/КБ Луч/1.png',0)
        img2 = cv2.imread('/Users/zaha/Downloads/КБ Луч/2.png',0)
        
        diap1 = [img2-311, img2-281]
        img1 = diap1
        img1 = np.asarray(img1, dtype=np.uint8)
        ssd2 = sum(img1-img2)**2
        men2 = img1.mean() - img2.mean()
        N = 750000
        
        R2 = ssd2 / N - (men2**2)
        R2 = np.asarray(R2, dtype=np.uint8)
        print('Вывести информацию о размере массиве R(d) изображения',R2.shape, '\nКоличество пикселей:', R2.size, '\nМассив R(d):\n', R2)
        d2 = np.amin(R2)
        print('Диспаритет:', d2)
        
        
    elif  answer == '3':
        
        print('Вывевести преобразованные изображения')
        img1 = cv2.imread('/Users/zaha/Downloads/КБ Луч/1.png',0)
        img2 = cv2.imread('/Users/zaha/Downloads/КБ Луч/2.png',0)
        rows,cols = img2.shape
        M = np.float32([[1,0,-249],[0,1,0]])
        dst = cv2.warpAffine(img2,M,(cols,rows))
        dst2 = cv2.addWeighted(img1,1,dst,1,0)
        cv2.namedWindow('image',cv2.WINDOW_NORMAL)
        cv2.imshow('image',dst2)
        
        rows,cols = img2.shape
        M = np.float32([[1,0,209],[0,1,0]])
        dst3 = cv2.warpAffine(img1,M,(cols,rows))
        dst4 = cv2.addWeighted(img2,1,dst3,1,0)
        cv2.namedWindow('image',cv2.WINDOW_NORMAL)
        cv2.imshow('image2',dst4)

        cv2.waitKey(0)
        cv2.destroyAllWindows()

else:()

        
    
    

1 - Построить карту диспаритета при изветном диапозоне сдвига диспаритета от 283 до 311
2 - Построить карту диспаритета при изветном диапозоне сдвига диспаритета от -311 до -283
3 - Вывевести преобразованные изображения (1/2/3)1
Вывести информацию о размере массиве R(d) изображения (750, 1000) 
Количество пикселей: 750000 
Массив R(d):
 [[249 249 249 ... 249 249 249]
 [249 249 249 ... 249 249 249]
 [249 249 249 ... 249 249 249]
 ...
 [249 249 249 ... 249 249 249]
 [249 249 249 ... 249 249 249]
 [249 249 249 ... 249 249 249]]
Диспаритет: 249
1 - Построить карту диспаритета при изветном диапозоне сдвига диспаритета от 283 до 311
2 - Построить карту диспаритета при изветном диапозоне сдвига диспаритета от -311 до -283
3 - Вывевести преобразованные изображения (1/2/3)2
Вывести информацию о размере массиве R(d) изображения (750, 1000) 
Количество пикселей: 750000 
Массив R(d):
 [[209 209 209 ... 209 209 209]
 [209 209 209 ... 209 209 209]
 [209 209 209 ... 209 209 209]
 ...
 [209 209 209 ..