In [1]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3],[2, 5, 6], [6, 7, 4]])
print('Матрица:\n', a)

Матрица:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


In [5]:
b = np.eye(5)
print('Единичная матрица:\n', b)

Единичная матрица:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
c = np.ones((7, 5))
print('Матрица состоящая из одних едениц:\n', c)

Матрица состоящая из одних едениц:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
v = np.arange(0, 24, 2)
print('Вектор столбец:\n', v)

Вектор столбец:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]


In [9]:
d = v.reshape((3, 4))
print('Матрица:\n', d)

Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [13]:
d = v.reshape((3, 4))
print('Матрица:\n', d)

Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [14]:
print('Второй элемент третьей строки:\n', d[2, 1])

второй элемент третьей строки:
 18


In [17]:
print('Вторая строка матрицы:\n', d[1, :])
print('Четвёртый столбец матрицы:\n', d[:, 3])

Вторая строка матрицы:
 [ 8 10 12 14]
Четвёртый столбец матрицы:
 [ 6 14 22]


In [18]:
print('Элементы матрицы с кординатами(1, 2) и (0, 3):\n', d[[1, 0], [2, 3]])

Элементы матрицы с кординатами(1, 2) и (0, 3):
 [12  6]


In [19]:
# Векторы , вектор-строки и вектор-стобцы
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

In [21]:
print('Вектор:\n', a)
print('Его размерность так же не изменилось:\n', a.shape)
print('Транспорнированный двумерный массив:\n', b)
print('Его размерность так же не изменилось:\n', b.shape)

Вектор:
 [1 2 3]
Его размерность так же не изменилось:
 (3,)
Транспорнированный двумерный массив:
 [[1]
 [2]
 [3]]
Его размерность так же не изменилось:
 (3, 1)


In [22]:
a = a.T

In [23]:
b = b.T

In [24]:
print('Вектор:\n', a)
print('Его размерность  изменилось:\n', a.shape)
print('Транспорнированный двумерный массив:\n', b)
print('Его размерность так же  изменилось:\n', b.shape)

Вектор:
 [1 2 3]
Его размерность  изменилось:
 (3,)
Транспорнированный двумерный массив:
 [[1 2 3]]
Его размерность так же  изменилось:
 (1, 3)


In [27]:
# 4 Умножение матриц и столбцов
a = np.array([[1, 0],[0, 1]])
b = np.array([[4, 1],[2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)

In [28]:
print('Матрица:\n',a)
print('Матрица:\n',b)
print('Результат умножения функцией:\n', r1)
print('Результат умножения методом:\n', r2)

Матрица:
 [[1 0]
 [0 1]]
Матрица:
 [[4 1]
 [2 2]]
Результат умножения функцией:
 [[4 1]
 [2 2]]
Результат умножения методом:
 [[4 1]
 [2 2]]


In [29]:
c = np.array([1, 2])
r3 = b.dot(c)

In [30]:
print('Матрица:\n',b)
print('Матрица:\n',c)
print('Результат умножения функцией:\n', r3)

Матрица:
 [[4 1]
 [2 2]]
Матрица:
 [1 2]
Результат умножения функцией:
 [6 6]


In [31]:
r = a * b

In [32]:
print('Матрица:\n',a)
print('Матрица:\n',b)
print('Результат умножения функцией:\n', r)

Матрица:
 [[1 0]
 [0 1]]
Матрица:
 [[4 1]
 [2 2]]
Результат умножения функцией:
 [[4 0]
 [0 2]]


In [33]:
# Транспонирование матриц 
a = np.array([[1, 2],[3, 4]])
b = np.transpose(a)
c = a.T

In [34]:
print('Матрица:\n',a)
print('Транспонирование функцией:\n',b)
print('Транспонирование методом:\n', c)

Матрица:
 [[1 2]
 [3 4]]
Транспонирование функцией:
 [[1 3]
 [2 4]]
Транспонирование методом:
 [[1 3]
 [2 4]]


In [46]:
# Определитель матрицы 
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)

In [47]:
print('Матрица:\n',a)
print('Определитель:\n',det)

Матрица:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Определитель:
 -1.0


In [48]:
# Ранг матрицы
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
r = np.linalg.matrix_rank(a)

In [49]:
print('Матрица:\n',a)
print('Ранг матрицы:\n',r)

Матрица:
 [[1 2 3]
 [1 1 1]
 [2 2 2]]
Ранг матрицы:
 2


In [50]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])
c = np.array([2, 3, 5])
m = np.array([a, b, c])

In [51]:
print(np.linalg.matrix_rank(m) == m.shape[0])

True


In [52]:
# Обращение матриц
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)

In [54]:
print('Матрица:\n',a)
print('Обратная матрица:\n',b)
print('Прозведение А на обратную матрицу дожна быть едичной:\n',a.dot(b))

Матрица:
 [[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]
Обратная матрица:
 [[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]
Прозведение А на обратную матрицу дожна быть едичной:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
# Собственные числа и собственные вектора 
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [56]:
print('Матрица:\n',a)
print('Собственные числа:\n',w)
print('Собственные векторы:\n', v)

Матрица:
 [[-1 -6]
 [ 2  6]]
Собственные числа:
 [2. 3.]
Собственные векторы:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [58]:
# Комплексные числа в питоне
a = 3 + 2j
b = 1j

In [59]:
print('Комплексное число с:\n', a)
print('Комплексное число с:\n', b)

Комплексное число с:
 (3+2j)
Комплексное число с:
 1j


In [62]:
c = a * a
d = a / (4 - 5j)

In [64]:
print('Комплексное число с:\n', c)
print('Комплексное число d:\n', d)

Комплексное число с:
 (5+12j)
Комплексное число d:
 (0.0487804878048781+0.5609756097560976j)
